name: 'Get Unity project name'
description: 'Get Unity project name'
outputs:
  projectName:
    description: "Project name"
    value: ${{ steps.project_name.outputs.projectName }}
  projectNameNoSpaces:
    description: "Project name with underscores instead of spaces"
    value: ${{ steps.project_name.outputs.projectNameNoSpaces }}
runs:
  using: "composite"
  steps:
    - name: Get project name variable
      id: project_name
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/getname.sh
        projectname=$(${{ github.action_path }}/getname.sh)
        projectnamenospaces=${projectname// /_}
        echo "projectName=$projectname" >> $GITHUB_OUTPUT
        echo "projectNameNoSpaces=$projectnamenospaces" >> $GITHUB_OUTPUT
