name: 'Free disk space'
description: 'Free disk space'

runs:
  using: "composite"
  steps:
    - name: Free space before build
      shell: bash
      run: |
        echo "=============================================================================="
        echo "Freeing up disk space on CI system"
        echo "=============================================================================="

        echo "=================="
        echo "Disk space before sudo apt-get remove -y 'php.*':"
        df -h
        
        sudo apt-get remove -y 'php.*'
        
        echo "Disk space after:"
        df -h
        echo "------------------"
        echo ""
        
        echo "=================="
        echo "Disk space before sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel:"
        df -h
        
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        
        echo "Disk space after:"
        df -h
        echo "------------------"
        echo ""
        
        echo "=================="
        echo "Disk space before sudo apt-get autoremove -y:"
        df -h
        
        sudo apt-get autoremove -y
        
        echo "Disk space after:"
        df -h
        echo "------------------"
        echo ""
        
        echo "=================="
        echo "Disk space before sudo apt clean:"
        df -h
        
        sudo apt clean
        
        echo "Disk space after:"
        df -h
        echo "------------------"
        echo ""

        #echo "Listing 100 largest packages"
        #dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        #echo "Removing large packages"
        #sudo apt-get remove -y '^ghc-8.*'
        #sudo apt-get remove -y '^dotnet-.*'
        #sudo apt-get remove -y '^llvm-.*'
        #sudo apt-get remove -y 'php.*'
        #sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        #sudo apt-get autoremove -y
        #sudo apt-get clean
        #df -h

        echo "Removing large directories"
        # https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh
        echo "=================="
        echo "Disk space before rm -rf /usr/share/dotnet/:"
        df -h
        
        rm -rf /usr/share/dotnet/
        
        echo "Disk space after:"
        df -h
        echo "------------------"
        echo ""

        # https://github.com/actions/virtual-environments/issues/709#issuecomment-612569242
        echo "=================="
        echo "Disk space before rm -rf "/usr/local/share/boost":"
        df -h
        
        rm -rf "/usr/local/share/boost"
        
        echo "Disk space after:"
        df -h
        echo "------------------"
        echo ""

        # Discarded
        #sudo swapoff -a
        #sudo rm -f /swapfile
        #rm -rf "$AGENT_TOOLSDIRECTORY"  This can break Python
        #docker rmi $(docker images -q)  # removing docker images breaks appleboy/telegram-action action.
