name: 'Notify'
description: 'Send a message'
inputs:
  notifyPlatform:
    required: true
    description: 'Platform to send the message.'
  message:
    required: true
    description: 'Message to send'
  # Telegram
  TELEGRAM_TOKEN:
    required: false
    default: ''
    description: 'TODO'
  TELEGRAM_CHAT_ID:
    required: false
    default: ''
    description: 'TODO'
  # Discord
  DISCORD_WEBHOOK_ID:
    required: false
    default: ''
    description: 'TODO'
  DISCORD_WEBHOOK_TOKEN:
    required: false
    default: ''
    description: 'TODO'

runs:
  using: "composite"
  steps:
    # Telegram
    - name: Send notification to Telegram
      if: ${{ inputs.notifyPlatform == 'Telegram'}}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.TELEGRAM_CHAT_ID }}
        token: ${{ inputs.TELEGRAM_TOKEN }}
        message: ${{ inputs.message }}
        
    # Discord
    - name: Send notification to Discord
      if: ${{ inputs.notifyPlatform == 'Discord'}}
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ inputs.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ inputs.DISCORD_WEBHOOK_TOKEN }}
        message: ${{ inputs.message }}
