name: 'Notify'
description: 'Send a message'
inputs:
  notifyPlatform:
    required: true
    description: 'Platform to send the message.'
  message:
    required: true
    description: 'Message to send'

runs:
  using: "composite"
  steps:
    # Telegram
    - name: Send notification to Telegram
      if: ${{ inputs.notifyPlatform == 'Telegram'}}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ env.TELEGRAM_CHAT_ID }}
        token: ${{ env.TELEGRAM_TOKEN }}
        message: ${{ inputs.message }}
        
    # Discord
    - name: Send notification to Discord
      if: ${{ inputs.notifyPlatform == 'Discord'}}
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ env.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ env.DISCORD_WEBHOOK_TOKEN }}
        message: ${{ inputs.message }}
