name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      base64_json:
        type: string
        required: true

jobs:
  decode_input:
    name: Parse base64 input
    runs-on: ubuntu-latest
    outputs:
      input: ${{ steps.decode.outputs.input }}
    steps:
      - name: Decode input
        id: decode
        run: |
          input=$(echo "${{ inputs.base64_json }}" | base64 --decode)
          echo "$input"
          echo "input<<_EOF_" >> $GITHUB_OUTPUT
          echo "$input" >> $GITHUB_OUTPUT
          echo "_EOF_" >> $GITHUB_OUTPUT
    
  build_and_deploy:
    needs: [ decode_input ]
    strategy:
      matrix:
        json_input: ${{ fromJson(needs.decode_input.outputs.input) }}
    uses: mnicolas94/facticus-deploy/.github/workflows/workflow_call.yml@feat/several_builds_one_workflow
    with:
      json_input: ${{ matrix.json_input }}
    secrets: inherit