name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      base64_json:
        type: string
        required: true

jobs:
  decode_input:
    name: Parse base64 input
    runs-on: ubuntu-latest
    outputs:
      input: ${{ steps.decode.outputs.input }}
    steps:
      - name: Decode input
        id: decode
        run: |
          input=$(echo "${{ inputs.base64_json }}" | base64 --decode)
          echo "$input"
          echo "input<<_EOF_" >> $GITHUB_OUTPUT
          echo "$input" >> $GITHUB_OUTPUT
          echo "_EOF_" >> $GITHUB_OUTPUT
  
  build_and_deploy:
    needs: [ decode_input ]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.decode_input.outputs.input) }}
    uses: mnicolas94/facticus-deploy/.github/workflows/workflow_call.yml@v0.6.18
    with:
      json_input: ${{ toJson(matrix) }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      ANDROID_KEYSTORE_NAME: ${{ secrets.ANDROID_KEYSTORE_NAME }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
      ANDROID_KEYALIAS_NAME: ${{ secrets.ANDROID_KEYALIAS_NAME }}
      ANDROID_KEYALIAS_PASS: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
      DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      ITCH_BUTLER_CREDENTIALS: ${{ secrets.ITCH_BUTLER_CREDENTIALS }}
      ITCH_GAME: ${{ secrets.ITCH_GAME }}
      ITCH_USER: ${{ secrets.ITCH_USER }}
      TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      PLAY_STORE_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
      PLAY_STORE_PACKAGE_NAME: ${{ secrets.PLAY_STORE_PACKAGE_NAME }}