name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      json_parameters:  # TODO change name to indicate is base64
        type: string
        required: true

jobs:
  decode_input:
    name: Parse base64 input
    runs-on: ubuntu-latest
    outputs:
      input: ${{ steps.decode.outputs.input }}
    steps:
      - name: Decode input
        id: decode
        run: |
          input=$(echo "${{ inputs.json_parameters }}" | base64 --decode)
          echo "$input"
          echo "input<<_EOF_" >> $GITHUB_OUTPUT
          echo "$input" >> $GITHUB_OUTPUT
          echo "_EOF_" >> $GITHUB_OUTPUT
    
  run:
    needs: [ decode_input ]
    uses: mnicolas94/facticus-deploy/.github/workflows/workflow_call.yml@feat/several_builds_one_workflow
    with:
      json_input: ${{ needs.decode_input.outputs.input }}
    secrets: inherit