name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      json_parameters:
        type: string
        required: true

jobs:
  run:
    uses: mnicolas94/facticus-deploy/.github/workflows/workflow_call.yml@main
    with:
      json_parameters: ${{ inputs.json_parameters }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      ANDROID_KEYSTORE_NAME: ${{ secrets.ANDROID_KEYSTORE_NAME }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
      ANDROID_KEYALIAS_NAME: ${{ secrets.ANDROID_KEYALIAS_NAME }}
      ANDROID_KEYALIAS_PASS: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      ITCH_BUTLER_CREDENTIALS: ${{ secrets.ITCH_BUTLER_CREDENTIALS }}
      ITCH_GAME: ${{ secrets.ITCH_GAME }}
      ITCH_USER: ${{ secrets.ITCH_USER }}
      PLAY_STORE_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
      PLAY_STORE_PACKAGE_NAME: ${{ secrets.PLAY_STORE_PACKAGE_NAME }}