name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      json_parameters:
        type: string
        required: true

jobs:
  run:
    uses: mnicolas94/facticus-deploy/.github/workflows/workflow_call.yml@v0.6.29
    with:
      json_parameters: ${{ inputs.json_parameters }}
    secrets: inherit