name: Test

on:
  workflow_dispatch:
    inputs:
      base64:
        type: string
        required: true
      json:
        type: string
        required: true

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: parse base64
        run: |
          echo b
      - name: run for loop
        run: |
          echo b