name: Build and deploy with json file as input

on:
  workflow_call:
    inputs:
      json_file:
        type: string
        required: true
      

jobs:
  read_input:
    name: Read json input for Deploy
    runs-on: ubuntu-latest
    outputs:
      input: ${{ steps.read.outputs.input }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Read input from json file
        id: read
        run: |
          file=${{ github.workspace }}/.github/workflows/${{ inputs.json_file }}
          input=$(cat $file)
          echo "$input"
          echo "input<<_EOF_" >> $GITHUB_OUTPUT
          echo "$input" >> $GITHUB_OUTPUT
          echo "_EOF_" >> $GITHUB_OUTPUT
          
  build_deploy:
    uses: mnicolas94/facticus-deploy/.github/workflows/workflow_call.yml@v0.6.34
    needs: [ read_input ]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.read_input.outputs.input) }}
    with:
      json_input: ${{ toJson(matrix) }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      ANDROID_KEYSTORE_NAME: ${{ secrets.ANDROID_KEYSTORE_NAME }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
      ANDROID_KEYALIAS_NAME: ${{ secrets.ANDROID_KEYALIAS_NAME }}
      ANDROID_KEYALIAS_PASS: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
      DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      ITCH_BUTLER_CREDENTIALS: ${{ secrets.ITCH_BUTLER_CREDENTIALS }}
      ITCH_GAME: ${{ secrets.ITCH_GAME }}
      ITCH_USER: ${{ secrets.ITCH_USER }}
      TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      PLAY_STORE_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
      PLAY_STORE_PACKAGE_NAME: ${{ secrets.PLAY_STORE_PACKAGE_NAME }}
